# config_dqn.yaml
model_name: DQN
learning_rate: 0.001
episodes: 5000
batch_size: 32
gamma: 0.99
epsilon_start: 1.0
epsilon_min: 0.01
epsilon_decay: 0.995
hidden_layers: [64, 64]  # Hidden layers with 64 units each
replay_buffer_size: 10000
target_update_frequency: 10
